// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwyVUWWaX7dpITmMxFfbh4oZSkP8_FrE8',
    appId: '1:77964537456:web:1b8d6f2c11de1e5a3e0eb5',
    messagingSenderId: '77964537456',
    projectId: 'ecochef-ai-3e0e9',
    authDomain: 'ecochef-ai-3e0e9.firebaseapp.com',
    storageBucket: 'ecochef-ai-3e0e9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn_Hg8OvffCP58BFwZ17kmXLLb2EtZ6Qo',
    appId: '1:77964537456:android:a721ead65f8dc23c3e0eb5',
    messagingSenderId: '77964537456',
    projectId: 'ecochef-ai-3e0e9',
    storageBucket: 'ecochef-ai-3e0e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw1-GIYgte6F7xGr35K6DQFtIaOOW7AvU',
    appId: '1:77964537456:ios:e8af771eda8989b33e0eb5',
    messagingSenderId: '77964537456',
    projectId: 'ecochef-ai-3e0e9',
    storageBucket: 'ecochef-ai-3e0e9.firebasestorage.app',
    iosBundleId: 'com.example.ecochefAi',
  );
}
